name: easy_audience_network
description:
  Facebook Audience Network plugin for Flutter apps. You can show Facebook Banner
  ads, Interstitial ads, Rewarded video ads and Native ads though this plugin.

version: 0.0.6

homepage: https://github.com/nooralibutt/audience_network_flutter

environment:
  sdk: ^3.5.3
  flutter: '>=2.0.6'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.dsi.easy_audience_network
        pluginClass: FacebookAudienceNetworkPlugin
      ios:
        pluginClass: FacebookAudienceNetworkPlugin
